### ISSUE TITLE
SCP feature

### ISSUE THREAD

**Issue by bigloupe** [anand1st/sshd-shell-spring-boot#10]
Hi Nithyanandan Natchimuthu,

Is-it possible to do scp with your extension and specify directory to host files ?
Thanks,

Cédric

**Comment by anand1st** [comment]
It's done. I've only tested with scp and sftp command in OSX command line. Use version 3.4 for this. Note: Have not tested with WinSCP.

**Comment by bigloupe** [comment]
Thanks
