### ISSUE TITLE
How to configure a custom role

### ISSUE THREAD

**Issue by hhfdna** [anand1st/sshd-shell-spring-boot#17]
I want to define my own role instead of ADMIN, and only commands annotated with that role can be executed by the user with that role, something like this:
```java
    @SshdShellCommand(value = "demo-log", description = "log", roles = "ocas")
    public String demo(String arg) {
        System.out.println(">>>>>>>>>>>>>>>>>>>>>");
        demoJobs.logging();
        return "done";
    }
```
and how to define ocas in application.yml?

btw, why i can see all system commands once i logged in with a non-admin user?

**Comment by anand1st** [comment]
May I know which version you're using? And if possible, the properties you have set in your application.yml? Will give me a clearer picture on what settings you have used.
