### ISSUE TITLE
install with mvn fail

### ISSUE THREAD

**Issue by lxholding** [anand1st/sshd-shell-spring-boot#3]
[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project com.namedfish:api:war:1.0-SNAPSHOT: Failed to collect dependencies at io.github.anand1st:sshd-shell-spring-boot-starter:pom:2.0: Failed to read artifact descriptor for io.github.anand1st:sshd-shell-spring-boot-starter:pom:2.0: Could not find artifact io.github.anand1st:sshd-shell-spring-boot-parent:pom:2.0

**Comment by lxholding** [comment]
Could not find artifact io.github.anand1st:sshd-shell-spring-boot-parent

**Comment by anand1st** [comment]
My mistake. Parent pom wasn't released. Version 2.1 will not have dependency on parent pom and should work just fine. Might take a while to appear Central maven repository.
