### ISSUE TITLE
Actuator command tries to autowire endpoint even if deactivated

### ISSUE THREAD

**Issue by fonimus** [anand1st/sshd-shell-spring-boot#8]
Hello,

Thanks for this started, it looks very promising to replace crash.

Could you add condition (@ConditionalOnProperty ?) to not have this command when endpoint is disabled (which is the default value for shutdown but could be deactivated by used) ?

Also, why not enabling auto configuration by default when we specifically add starter dependency ?

Thanks

**Comment by fonimus** [comment]
I have created a pull request with a working example: https://github.com/anand1st/sshd-shell-spring-boot/pull/9

**Comment by anand1st** [comment]
Thank you for this. I will write additional tests to verify it works as expected according to flags set. Will make a new release after everything checks out.

**Comment by fonimus** [comment]
Great, thank you !

I have another question, are you currently working on being able to handle multiple arguments ?
Like method(String arg1, int arg2), and then invoke method with parameters parsed from command line ?
Is that something you'd like to have a merge request of ?

**Comment by anand1st** [comment]
My opinion is that if a user wants to handle multiple arguments, they would write this in a key value format i.e. 
`<command> <subcommand> --key1 value1 --key2 value2`

Or use the interactive approach (see EchoCommand in sshd-shell-spring-boot-test-app project).

I'm of two minds of having multiple arguments as it would add more complexity in the code base. To solve the above, there are two ways.
1) A utility method in ConsoleIO that takes in the arg and returns a Map of key-values to be used in the command.
2) Migrate to spring-shell which does this all for us automatically.

I'm more inclined to the second. But in the meantime, a utility method should help do this.
